"""empty message

Revision ID: 4769c4417bf9
Revises: 596f55a2b8fc
Create Date: 2025-01-29 11:26:01.620338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4769c4417bf9'
down_revision: Union[str, None] = '596f55a2b8fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacentrymodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used_id', sa.Integer(), nullable=True))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacentrymodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('used_id')

    # ### end Alembic commands ###
